### ISSUE TITLE
Theme icon not visible using dark themes

### ISSUE THREAD

**Issue by manekenpix** [PedroFonsecaDEV/dark-theme-color-blind#1]
When looking up your extension in VSCode, it shows up like this:
![image](https://user-images.githubusercontent.com/23108901/99819346-5977c700-2b1d-11eb-832a-5b5220b809a8.png)

 I think it'd be a good idea to have an icon that works with both dark and light themes. (I'm using Bearded Theme Black Emerald).

**Comment by PedroFonsecaDEV** [comment]
@manekenpix Thanks.
I fixed it creating a background colour for the icon.
