### ISSUE TITLE
How to enhance text selection.

### ISSUE THREAD

**Issue by tgraham2** [PedroFonsecaDEV/dark-theme-color-blind#3]
First - this is great! Thank you so much. There are probably 100's of people saying the same thing. I was about ready to quit trying to use VSC.

However I would like to enhance the highlighting of selected text. (When you hold the mouse button down and move the cursor). What is the easiest way to brighten the selected text?

**Comment by PedroFonsecaDEV** [comment]
Hi @tgraham2, 

Thanks for reaching out.
I would recommend you read the following docs to customize the colors:
[customizing-a-color-theme doc](https://code.visualstudio.com/docs/getstarted/themes#_customizing-a-color-theme)

[vscode custom colors reference](https://code.visualstudio.com/api/references/theme-color)
